import { useEffect, useState } from 'react'
import { downloadReportById, getReport } from '../api/reports'
import { useAuth } from '../context/AuthContext'
import { API_BASE_URL } from '../api/client'
import '../styles/dashboard.css'
import '../styles/change-request-form.css'
import '../styles/change-requests-list.css'
import '../styles/workflow.css'

const RISK_CLASS = { low: 'badge--green', medium: 'badge--amber', high: 'badge--orange', critical: 'badge--red' }

function formatDateTime(isoString) {
  if (!isoString) return '—'
  try {
    return new Date(isoString).toLocaleString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    })
  } catch {
    return isoString
  }
}

/** Module 24: a report's view page - a metadata card (spec section 12: id,
 * CR, title, version, analysis version, status, risk, generated by/at) plus
 * the actual PDF embedded right below it, fetched once as a blob (an
 * <iframe src="..."> can't carry the Authorization header this endpoint
 * requires) and shown in the browser's own PDF viewer - the same PDF
 * "Download" produces, never a second, separately-built rendering of the
 * same report content (confirmed with the project owner before building
 * this page). */
export default function ReportDetailPage({ reportId, onBack, onOpenChangeRequest }) {
  const { token } = useAuth()
  const [report, setReport] = useState(null)
  const [error, setError] = useState(null)
  const [pdfUrl, setPdfUrl] = useState(null)
  const [pdfError, setPdfError] = useState(null)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    let cancelled = false
    setError(null)
    getReport(reportId, token)
      .then((data) => {
        if (!cancelled) setReport(data)
      })
      .catch((err) => {
        if (!cancelled) setError(err.message || 'Could not load this report.')
      })
    return () => {
      cancelled = true
    }
  }, [reportId, token])

  useEffect(() => {
    let cancelled = false
    let objectUrl = null
    setPdfError(null)
    setPdfUrl(null)

    fetch(`${API_BASE_URL}/api/reports/${reportId}/download`, {
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
      .then(async (response) => {
        if (!response.ok) {
          let detail
          try {
            detail = (await response.json())?.detail
          } catch {
            detail = null
          }
          const message =
            typeof detail === 'string' ? detail : detail?.message || 'Could not load the PDF preview.'
          throw new Error(message)
        }
        return response.blob()
      })
      .then((blob) => {
        if (cancelled) return
        objectUrl = URL.createObjectURL(blob)
        setPdfUrl(objectUrl)
      })
      .catch((err) => {
        if (!cancelled) setPdfError(err.message || 'Could not load the PDF preview.')
      })

    return () => {
      cancelled = true
      if (objectUrl) URL.revokeObjectURL(objectUrl)
    }
  }, [reportId, token])

  async function handleDownload() {
    setDownloading(true)
    setPdfError(null)
    try {
      await downloadReportById(
        reportId,
        token,
        report ? `${report.change_request_code}-v${report.version}-report.pdf` : undefined
      )
    } catch (err) {
      setPdfError(err.message || 'Could not download this report.')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="cr-detail-shell">
      <nav className="breadcrumbs" aria-label="Breadcrumb">
        <button type="button" className="breadcrumb-link" onClick={onBack}>
          Reports
        </button>
        <span className="breadcrumb-separator">/</span>
        <span className="breadcrumb-current">{report ? `${report.change_request_code} · v${report.version}` : `Report #${reportId}`}</span>
      </nav>

      {error && <p className="cr-list-status-text cr-list-status-text--error">{error}</p>}

      {report && (
        <>
          <div className="cr-detail-heading">
            <div>
              <h1>
                {report.change_request_code} · Version {report.version}
              </h1>
              <div className="cr-detail-badges">
                <span className="badge badge--gray">{report.cr_status_label}</span>
                {report.risk_bucket ? (
                  <span className={`badge ${RISK_CLASS[report.risk_bucket.toLowerCase()] || 'badge--gray'}`}>
                    {report.risk_bucket} risk
                  </span>
                ) : (
                  <span className="badge badge--gray">Not analyzed</span>
                )}
                {report.is_historical_pull && <span className="badge badge--indigo">Historical</span>}
                {!report.is_current_version && (
                  <span className="badge badge--amber" title="A newer version of this change request now exists.">
                    Outdated
                  </span>
                )}
              </div>
            </div>
            <div className="approval-actions-cell">
              <button
                type="button"
                className="cr-btn cr-btn--secondary"
                onClick={() => onOpenChangeRequest?.(report.change_request_id)}
              >
                Open Change Request
              </button>
              <button type="button" className="cr-btn cr-btn--primary" disabled={downloading} onClick={handleDownload}>
                {downloading ? 'Working…' : 'Download PDF'}
              </button>
            </div>
          </div>

          <section className="cr-detail-section">
            <h2 className="cr-section-title">Report Details</h2>
            <dl className="cr-detail-grid">
              <dt>Report ID</dt>
              <dd>#{report.report_id}</dd>
              <dt>Change Request</dt>
              <dd>
                {report.change_request_code} — {report.change_request_title}
              </dd>
              <dt>Change Request Version</dt>
              <dd>{report.version}</dd>
              <dt>Analysis Version</dt>
              <dd>{report.has_analysis ? report.analysis_version : 'Analysis unavailable for this version.'}</dd>
              <dt>Current Status</dt>
              <dd>{report.cr_status_label}</dd>
              <dt>Risk</dt>
              <dd>{report.risk_bucket || 'Not analyzed'}</dd>
              <dt>Generated By</dt>
              <dd>{report.generated_by_name}</dd>
              <dt>Generated At</dt>
              <dd>{formatDateTime(report.generated_at)}</dd>
              {report.pull_count > 1 && (
                <>
                  <dt>Times Downloaded</dt>
                  <dd>{report.pull_count}</dd>
                </>
              )}
            </dl>
          </section>

          <section className="cr-detail-section">
            <h2 className="cr-section-title">Report Content</h2>
            {pdfError && <p className="cr-list-status-text cr-list-status-text--error">{pdfError}</p>}
            {!pdfError && !pdfUrl && <p className="cr-list-status-text">Loading report…</p>}
            {pdfUrl && (
              <iframe
                title={`Report ${report.report_id}`}
                src={pdfUrl}
                style={{ width: '100%', height: '80vh', border: '1px solid #d0d5dd', borderRadius: '8px' }}
              />
            )}
          </section>
        </>
      )}
    </div>
  )
}
